name: openur-backend-to-beanstalk

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          distribution: 'corretto'
          java-version: '17'

    - name: Grant execute permission for gradlew
      working-directory: ./app
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew clean build
      shell: bash

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDDTHHmm
        utcOffset: "+09:00"

    - name: Generate deployment package
      run: |
        mkdir -p deploy
        cp app/build/libs/app.jar deploy/openur-1.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions deploy/.ebextensions
        cd deploy && zip -r openur-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}} .

    - name: Build and Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "openur"
        environment_name: "Openur-env"
        version_label: "v${{ github.run_number }}"
        region: "ap-northeast-2"
        deployment_package: "deploy/openur-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip"
        wait_for_deployment: true
